### ISSUE TITLE
Integrate Login.gov service into front-end and back-end

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#109]
Integrate the Login.gov web service into the web-app and web-api authentication process

Documentation: https://developers.login.gov/overview/

For this ticket, it will create a login process via Login.gov for a committee account admin role that is linked to only 1 committee account.

Future tickets will expand on this process to include users linked to more than one committee account and roles beyond committee account admin

**Tasks**
- [ ] Set up initial landing page with a "login" and "register" button that redirects to Login.gov
- [ ] Login.gov will return the authenticated user to the dashboard page with the legalese pop up displayed.
- [ ] The authenticated user session will be linked to the appropriate user record in the authentication_account table in the database

**Acceptance Criteria**
[See fecfile-web-app #92](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/92)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
Duplicate of [fecfile-web-app #92](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/92)
