### ISSUE TITLE
UI: Update Toggle Component Design

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1294]
### User Story
As a UX Principal, I would like the Toggle component updated across the site to match the FEC style guide.

### Reference
Please review this source as a reference point will updating the component
https://fec-pattern-library.app.cloud.gov/components/detail/horizontal.html

### Tasks
**Left side**
border-radius: 4px 0 0 4px;

**Right side**
border-radius: 0 4px 4px 0;

**Unselected**
border-color: #aeb0b5
background-color: #FFFFFF;
font-weight: 400
ON HOVER-
border-color: #E8E8E8
[No hover color change on the background-color. On hover text should stay black with white background]

**Selected**
border-color: #5b616b;
background-color: #d6d7d9;
font-weight: 700
ON HOVER-
border-color: #d6d7d9;

**Constants to both sides of the toggle:**
font-family: karla,sans-serif;
font-size: 14px
color: #212121
border: 3px;
cursor: pointer;

### DEV Notes
When initial state is no selection please use the Unselected state for both sides

### QA Notes
- [x] BA/Design Quality Checklist complete
- [ ] test toggle on Conduit earmark
- [ ] test on Create a new report

### Wireframes
![Screenshot 2023-07-25 at 4.41.51 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8fc14ada-51bc-4e8e-82fe-801d34c6c486)

![1294 - Toggles.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/93f20683-e5aa-4efa-92b8-2ad550c3777a)

**Comment by MitchellTCG** [comment]
@toddlees please review before refinement meeting

**Comment by MitchellTCG** [comment]
@toddlees please review before refinement meeting

**Comment by MitchellTCG** [comment]
@GreggMoreland
UX Review complete

**Comment by GreggMoreland** [comment]
BA Review complete

**Comment by mjtravers** [comment]
Passes CR. Sending to QA. Ticket can be moved to QA after "on hold" removed.
Notes:
This can be tested on the Conduit Earmark
OLD VERSION:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWt1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b42960790748d7a0745ed9e427e9da030a45b150/image.png)

NEW VERSION:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXN1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9fdc667fc310b302a8b6c8e41d781bfa9a4855dc/image.png)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified Toggle components were updated per UX.   (Note:  QA reviewed this ticket with Mitchell and Dru).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlZuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f36201b409b8e963b91ae844729a191ff96cfae5/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjluQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eae1d2629a57b905df1524e0a29e0e6a1cbe9c1f/image.png)

QA Review Completed.  Moved to Stage Ready.
