### ISSUE TITLE
UI: Tables: Manage contacts: Update buttons

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1905]
Business Reason

  As the principal UX, I would like all tables to have continuity so users will have a similar experience throughout the site.

Tasks

  For the “+ New” button

*   [x] Change the name of the button to “Add contact”
*   [x] Change font-weight from 400 to 600
*   [x] Remove a random 8px margin to the right of the button
*   [x] Change the color of the button from #287538 to #F77B42
*   [x] Change the hover color from #0C602B to #F78D5B
*   [x] Change Text color to ***color: #212121***

For the “Restore deleted contact(s)” button

*   [x] Change font-weight from 400 to 600
*   [x] Make the hover color #164F85

1.  Current

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/74b700cd-b846-49f3-8611-ff84340bbc40](https://github.com/fecgov/fecfile-web-app/assets/25588182/74b700cd-b846-49f3-8611-ff84340bbc4))

1.  + Add contact button

       ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/f5e0692d-75bd-4017-afd7-6830901a1819](https://github.com/fecgov/fecfile-web-app/assets/25588182/f5e0692d-75bd-4017-afd7-6830901a181))

### QA Notes ###
 
 - [x] BA/Design Quality Checklist complete

### DEV Notes ###
 
  Wireframes

### Design ###
 
 null

[FECFILE-403](https://fecgov.atlassian.net/browse/FECFILE-403)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review noticed a couple things.   Change the name of the button to “Add contact”.   "contact" is lowered cased on button.

Change Manage Contacts to Manage contacts on the table name.  @MitchellTCG you were going to add this change in this ticket, but think we missed it.   Can this please be added and changed to match other table names ?

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/32e2cc6f-25d2-43ed-baa8-366d870daf2b)

______________________________________________________________________________________________________________________
@MitchellTCG @mjtravers @sasha-dresden returned to In-Progress for a few minor changes.

**Comment by MitchellTCG** [comment]
@sasha-dresden 
Pls make both changes for me. 
- [x] Manage contacts (lowercase c in the header)
- [ ] + Add contacts (lowercase c in button)

**Comment by toddlees** [comment]
Passes CR moving to QA

**Comment by WiseQA** [comment]
QA review verified the two changes were implemented on the "Manage contacts" page.

- [x] Manage contacts (lowercase c in the header)
- [x] + Add contacts (lowercase c in button)
______________________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/57c1e608-e20d-4a6c-8a3e-939dc60c989e)
________________________________________________________________________________________________________

QA Review Completed.   Moved to Stage Ready.
