### ISSUE TITLE
UI: Landing Page Redux: Update landing page for better responsive behavior

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-app#1907]
Business Reason

  As the principal UX, I would like the landing page to be cleaned up and responsive for a better overall user experience

Tasks

  Official website banner

  –

  "An official website of the..." will stay the same

Navigation bar

  –

  the background-color will be change from grey to ***#FFFFFF***

*   [x] have 64 px of space between to bottom of the nav box and the Headline text

Headline text

  –

  ***At 1400 and 1200***

  Headline text stays the same _BUT will be on one line._ 

  ***Made for filers. Built to work anywhere.***

*   [x] Change font-size from 32px to ***36px***
*   [x] Center text

***At 992, 768, and 576***

  Headline text stays the same _AND will be on TWO line._ 

  **Made for filers. 

  Built to work anywhere.**

*   [x] Change font-size from 32px to ***36px***
*   [x] Center text

Paragraph text

–

  ***At 1400, 1200, and 992***

  Paragraph text will stay the same but each sentence will be on it's own line

  **FECFile is free web-based software for electronic filing. 

  It allows users to create, review, and submit reports from anywhere.**

*   [x] Change font from Karla to ***Gandhi Serif***
*   [x] Change font-size from 14px to 18px

***At 768 and 576***

  Paragraph text will stay the same and wrap inside a 480px div

  ***FECFile is free web-based software for electronic filing. It allows users to create, review, and submit reports from anywhere.***

*   [x] Change font from Karla to ***Gandhi Serif***
*   [x] Change font-size from 14px to 18px

Buttons

–

*   [x] Have 32px of vertical space between paragraph text and buttons
*   [x] change the font-weight of both buttons to ***font-weight:600***
*   [x] Sign up with Login.gov background color: #35BDBB and text is #212121

Learn More

–

*   [x] center text

Hero image

–

1.  at 1400xxl and 1200xl

*   [x] Have 64 px of vertical space between learn more url and hero image
*   [x] Image size is 800px wide
*   [x] 100px down from the top of the hero image change the background-color to ***#0BACFA***.
*   [x] There should be 64px of space between the bottom of the hero image and the footer

1.  at 992lg

*   [x] Have 64 px of vertical space between learn more url and hero image
*   [x] Image size is 600px wide
*   [x] 100px down from the top of the hero image change the background-color to ***#0BACFA***.
*   [x] There should be 64px of space between the bottom of the hero image and the footer

1.  at 768md and 576sm

*   [x] Have 32px of vertical space between learn more url and hero image
*   [x] Image size is 480px wide
*   [x] 100px down from the top of the hero image change the background-color to ***#0BACFA***.
*   [x] There should be 64px of space between the bottom of the hero image and the footer

Footer

–

  Footer should NOT snap to the bottom of the page. It should work like ALL the other pages

Wireframe

1.  Current page

![](/attachments/11309?name=image-20240530-210152.png) [See image in Jira]([https://fecgov.atlassian.net/browse/FECFILE-401](https://fecgov.atlassian.net/browse/FECFILE-401)) [See image in Jira]([https://fecgov.atlassian.net/browse/FECFILE-401](https://fecgov.atlassian.net/browse/FECFILE-401))

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/fc093c00-4b19-495e-a5a6-21791d1ff439](https://github.com/fecgov/fecfile-web-app/assets/25588182/fc093c00-4b19-495e-a5a6-21791d1ff43))

1.  1400xxl

![](/attachments/11311?name=image-20240530-210222.png)

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/30dd8560-8839-4eb1-8cf2-5b37794088da](https://github.com/fecgov/fecfile-web-app/assets/25588182/30dd8560-8839-4eb1-8cf2-5b37794088d))

1.  1200xl

![](/attachments/11313?name=image-20240530-210239.png)

  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/9e785cd3-3696-4223-8e98-e9fd2a95c6cd](https://github.com/fecgov/fecfile-web-app/assets/25588182/9e785cd3-3696-4223-8e98-e9fd2a95c6c))

1.  992lg

![](/attachments/11310?name=image-20240530-210318.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/44702f3e-992d-4e96-89f8-4946a73acde9](https://github.com/fecgov/fecfile-web-app/assets/25588182/44702f3e-992d-4e96-89f8-4946a73acde))

1.  768md

![](/attachments/11316?name=image-20240530-210402.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/48af4bf7-5b0f-4892-bb4e-5f29de182904](https://github.com/fecgov/fecfile-web-app/assets/25588182/48af4bf7-5b0f-4892-bb4e-5f29de18290))

1.  576sm

![](/attachments/11314?name=image-20240530-210459.png)

1.  ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/ac1012fb-68a1-497b-abfc-b2bf08c1b6b5](https://github.com/fecgov/fecfile-web-app/assets/25588182/ac1012fb-68a1-497b-abfc-b2bf08c1b6b))

Assets

800 px wide image

![](/attachments/11312?name=image-20240530-210529.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/f7aa0c04-ec09-40b6-adbb-6f3cc2312b27](https://github.com/fecgov/fecfile-web-app/assets/25588182/f7aa0c04-ec09-40b6-adbb-6f3cc2312b2))

600px wide image

![](/attachments/11315?name=image-20240530-210614.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/fea865f5-277c-4384-b547-b1065e983275](https://github.com/fecgov/fecfile-web-app/assets/25588182/fea865f5-277c-4384-b547-b1065e98327))

480px wide image

![](/attachments/11308?name=image-20240530-210637.png)

![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/b76fd280-ba02-45d9-81a5-f458b58cfa80](https://github.com/fecgov/fecfile-web-app/assets/25588182/b76fd280-ba02-45d9-81a5-f458b58cfa8))

### QA Notes ###

 
  
  
  
  
  
  
 null

### DEV Notes ###

 
  
  
  
  
  
  
 null

### Design ###

 
  
  
  
  
  
  
 null/

[FECFILE-401](https://fecgov.atlassian.net/browse/FECFILE-401)

**Comment by MitchellTCG** [comment]
@JonellaCulmer pls review

**Comment by MitchellTCG** [comment]
@GreggMoreland pls review

**Comment by sasha-dresden** [comment]
@MitchellTCG couple questions

For the paragraph text At 1400, 1200, and 992, it says to  Change font from Karla to Gandhi Serif. I just want to confirm that this font change is only at those screen sizes?
Also for paragraph text at 1400, 1200, and 992 it says: "each sentence will be on it's own line". However the wireframes for those three sizes don't indicate that. Which is correct?

**Comment by MitchellTCG** [comment]
@sasha-dresden I updated the wires

**Comment by mjtravers** [comment]
@sasha-dresden There's a comment from the CR. Sending back to In Progress.

**Comment by JonellaCulmer** [comment]
Remove tips for treasurers here as well

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
During QA review and UX verification the text needs fixed on the Landing Page.    See screenshots below.

Landing page showing text displaying on one line (see highlighted text)  (This is incorrect)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/18762294-2f6f-4440-bbb0-a52ee7adbed9)

_______________________________________________________________________________________________________

Wireframe showing text should be two lines and a period after second sentence (see highlighted text)  (This is correct)

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/fb535946-212d-4e7f-a37a-d9b4efe6086e)

@MitchellTCG @mjtravers returned to In-progress for text format fix.

**Comment by MitchellTCG** [comment]
@sasha-dresden 
please make the line break in the headline break at 992 like the ACs
and add a period after anywhere[.]

**Comment by sasha-dresden** [comment]
Updated.



![Image](https://github.com/fecgov/fecfile-web-app/assets/149604256/938e4a15-5d53-437c-bc06-7e57772b7738)
![Image](https://github.com/fecgov/fecfile-web-app/assets/149604256/9859b955-1709-45d9-82af-6b277f77a1a6)
![Image](https://github.com/fecgov/fecfile-web-app/assets/149604256/305441b4-60a3-4a55-86c9-e51d106d7bd0)
![Image](https://github.com/fecgov/fecfile-web-app/assets/149604256/ec711a7c-45c9-4af9-a13b-02c627ea117c)
![Image](https://github.com/fecgov/fecfile-web-app/assets/149604256/100e4ec9-cda9-4b0e-8cd6-f4cf5cf3a270)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG @sasha-dresden @mjtravers per review with UX, the headline break should be 992 LG and 768 MED.   Verified period was added that part was corrected.

Moving back to In-progress for this fix.

**Comment by sasha-dresden** [comment]
1200 - 1 Line.
![Screenshot 2024-06-10 113844](https://github.com/fecgov/fecfile-web-app/assets/149604256/c88c8eb0-60a8-4c66-a95e-0a20376f8eca)

992 - 2 lines
![Screenshot 2024-06-10 113914](https://github.com/fecgov/fecfile-web-app/assets/149604256/65d143e2-3c82-4772-879c-aadccb1288cc)

768 - 2 lines
![Screenshot 2024-06-10 113932](https://github.com/fecgov/fecfile-web-app/assets/149604256/6260c967-7a62-46b2-9542-546d1d768c99)

**Comment by mjtravers** [comment]
Update to style made and passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified with UX, the headline break should be 992 LG and 768 MED was corrected per DEV screenshots above.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/42ab2f63-ff32-4880-b3ff-55ee381d6657)

QA Review Completed.  Moved to Stage Ready.
