### ISSUE TITLE
UI: FECFile Online Dashboard

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#1908]
Business Reason As the UX Principal, I would like to start iterating on the dashboard so it will more closely match the original intend of the page.

Acceptance Criteria

**Create placeholders for 3 different sections:**

1.  in-progress reports
2.  Cash-on-hand
3.  Recently submitted reports

In-progress –

*   [x] 558w by 404h div
*   [x] border-radius: 4px
*   [x] #E8E8E8
*   [x] Header: "In-progress reports"; 24px; Gandhi-serif bold; #212121
*   [x] Placeholder Card: White; 518x308; with 20px padding left and right
*   [x] Hyperlink: "Start a different report"; points to create report

Cash-on-hand –

*   [x] 558w by 154h div
*   [x] border-radius: 4px
*   [x] #E8E8E8
*   [x] Header: "Cash-on-hand"; 24px; Gandhi-serif bold; #212121
*   [x] Placeholder Card: White; 518x86: with 20px padding left and right

Recently submitted reports –

*   [x] 558w by 578h div
*   [x] border-radius: 4px
*   [x] #E8E8E8
*   [x] Header: "Recently submitted reports"; 24px; Gandhi-serif bold; #212121
*   [x] Placeholder Card: White; 518x482; with 20px padding left and right
*   [x] Hyperlink: "Manage reports"; points to create report

**1400xxl**

1.  In-progress reports Grey box = w558 x h404 White box = w518
2.  Cash on-hand Grey box = w558 x h154 White box = w518 x h86
3.  Recently submitted reports Grey box = w558 x h578 White box = w518 x 482

**1200xl**

1.  In-progress reports Grey box = w454 x h404 White box = w414
2.  Cash on-hand Grey box = w454 x h154 White box = w414 x h86
3.  Recently submitted reports Grey box = w454 x h578 White box = w414 x 482

**992lg**

1.  In-progress reports Grey box = w704 x h404 White box = w664
2.  Cash on-hand Grey box = w704 x h154 White box = w664 x h86
3.  Recently submitted reports Grey box = w704 x h578 White box = w664 x 482

**768md**

1.  In-progress reports Grey box = w512 x h404 White box = w472
2.  Cash on-hand Grey box = w512 x h154 White box = w472 x h86
3.  Recently submitted reports Grey box = w512 x h578 White box = w472 x 482

**576sm**

1.  In-progress reports Grey box = w512 x h404 White box = w472
2.  Cash on-hand Grey box = w512 x h154 White box = w472 x h86
3.  Recently submitted reports Grey box = w512 x h578 White box = w472 x 482

### QA Notes ###

 - [x] BA/Design Quality Checklist complete

### DEV Notes ###

  
 the fixed div width inside each breakpoint
- 1400xxl = 1136px
- 1200xl = 928px
- 992lg = 704px
- 768md = 512px
- 576sm = 512px

### Design ###

 Wireframes
 1400xxl
 –
 ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/59e645d9-3089-4558-a287-7fa931f13e42)

1200xl
 –
 ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/412bce07-2915-473d-8f2e-baf9e0a5de8b)

992lg
 –
 ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/aebacb58-df6f-4b9e-85de-b645a7647677)

768md
 –
 ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/bff5a42b-14aa-4fa9-b3af-c1eb76a7a4c1)

576sm
 –
 ![Image](https://github.com/fecgov/fecfile-web-app/assets/25588182/a509ab8e-80dc-4030-b538-d90d73de084b)

[FECFILE-400](https://fecgov.atlassian.net/browse/FECFILE-400)

**Comment by MitchellTCG** [comment]
@JonellaCulmer please review

**Comment by JonellaCulmer** [comment]
@MitchellTCG Do we want to reconsider the appearance if we're dropping the gray background elsewhere? I'm wondering if we should also drop the tips for treasurers now until we have a method to populate that section.

**Comment by MitchellTCG** [comment]
@GreggMoreland please review this ticket and place into ADTQR if it looks good to you

**Comment by MitchellTCG** [comment]
@MitchellTCG remove tips for treasurers

**Comment by AureliaKhorsand** [comment]
@MitchellTCG are you able to remove the tips for treasurers so this can be ready for the next sprint?

**Comment by MitchellTCG** [comment]
@JonellaCulmer 
Tips for treasurers removed from mocks

**Comment by sasha-dresden** [comment]
Development done. Need to code review with @MitchellTCG

**Comment by sasha-dresden** [comment]
Reviewed with @MitchellTCG and made some minor tweaks for centering the dashboard, font updates and spacing. And made the "Start a different report" open the "Create a Report" dialog on this page, rather than redirecting to the report page. Fixes in and PR created.

**Comment by mjtravers** [comment]
From CR:

The "Manage reports" link is going to the "Security notifications" page.

Should this ticket be populating the "In-progress Reports" section? If so, some of the report types are not displaying in the list.


![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/a1b604ae-ff73-4738-8bd4-c54a25b4c6af)

Sending ticket back to In Progress.

**Comment by sasha-dresden** [comment]
Ah, I see the issue. It only happens when you have not chosen to confirm for a year. I changed it from an href to angular's routerLink and it works as expected for that situation now.

As for the "In-progress Reports" section that's more of a work in progress. There will be a later ticket for building that out which will provide how that will function fully. All I wanted to do was make sure that when there are multiple reports the white boxes that will eventually be filled with data, are arranged properly. The screenshots showed 2 but the AC mentioned the total area, so I built this out as a placeholder till we get the official version.

**Comment by mjtravers** [comment]
@sasha-dresden Thanks for the clarification about the wireframes. That make sense.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@MitchellTCG @AureliaKhorsand the Acceptance Criteria states 4 different sections.   Verifying that there should only be 3 and not 4 sections.   Thanks

**Create placeholders for 4 different sections:**

1.  in-progress reports
2.  Cash-on-hand
3.  Recently submitted reports

**Comment by WiseQA** [comment]
@MitchellTCG verified states should be changed from 4 different sections to 3 different sections.   Per our review and discussion updated ticket as such.    Thanks !

**Comment by WiseQA** [comment]
QA review verified FECFile Online Dashboard updated with the current UX / Functionality only documented in this ticket.

Verified the following section placeholder's have been added to the dashboard.

1.  in-progress reports
2.  Cash-on-hand
3.  Recently submitted reports

_____________________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/9b114d09-2e97-4dd2-862a-47e538f04fae)
______________________________________________________________________________________

Select the "Start a different report >" link in the "In-progress reports" section.   
_______________________________________________________________________________________

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/b0027fa7-0794-406a-94d8-1a41a2ad499d)
________________________________________________________________________________

Verify "Create a new report" popup window is displayed and selecting a "Form Type" functionality is working.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/d6dfd2c9-6e9e-492a-a98b-2a29904560dc)
______________________________________________________________________________________

Select the "Manage reports >" link in the "Recently submitted reports" section.  

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/45f64db1-0625-444a-9e70-a47b35891252)
_________________________________________________________________________________________

Verify "Manage reports" page is displayed.

![Image](https://github.com/fecgov/fecfile-web-app/assets/96139912/1893fa79-05fe-4b9d-9710-06c40b52d0fd)

_____________________________________________________________________________________________

QA Review Completed.  Moved to Stage Ready.
