### ISSUE TITLE
Refactor test suite names and add missing transaction coverage to Cypress

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#762]
Currently, the Cypress e2e test suite is organized by sprint and ticket number. This has become problematic as the number of tests has grown in managing what tests are being run. This task is to refactor the organization of the e2e test suites to rename the test files to what they are testing rather than the ticket number and then group those files in directories that map roughly to the site navigation menu. (i.e. contacts, reports, transactions, users, etc)

***Tasks***
 1\. Reorganize and rename cypress test suite directories and file names to mirror the lighthouse names in organization. This is so that the test suites have the same name as the  tag of the page being tested (as best as possible).
 2\. Update the describe() and it() function description parameters to say, in human readable form, what the test is testing rather than containing a script or ticket number.
 3\. The following transactions were found to be missing from the transaction create tests and need to be added:

*   [x] EARMARK_MEMO
*   [x] INDIVIDUAL_JF_TRANSFER_MEMO
*   [x] INDIVIDUAL_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO
*   [x] INDIVIDUAL_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO
*   [x] PAC_JF_TRANSFER_MEMO

*   [x] PAC_NATIONAL_PARTY_RECOUNT_ACCOUNT
*   [x] PAC_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO
*   [x] PARTY_JF_TRANSFER_MEMO
*   [x] TRIBAL_JF_TRANSFER_MEMO
*   [x] TRIBAL_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO
*   [x] PAC_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO
*   [x] INDIVIDUAL_RECOUNT_RECEIPT
*   [x] TRIBAL_RECOUNT_RECEIPT
*   [x] PAC_RECOUNT_RECEIPT
*   [x] PARTY_RECOUNT_RECEIPT
*   [x] TRIBAL_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO

***Acceptance Criteria***
 The Cypress e2e report displays site features in output rather than sprint and ticket numbers. Transaaction create tests include the ones listed above in Task 3.

***QA Notes***
 These transaction were completed before Sprint 17 Started.
 Screen shots in comments show new names of test suites and the new output text of the e2e report output.

### QA Notes ###
**Tasks**
1. Reorganize and rename cypress test suite directories and file names to mirror the lighthouse names in organization. This is so that the test suites have the same name as the  tag of the page being tested (as best as possible).
2. Update the describe() and it() function description parameters to say, in human readable form, what the test is testing rather than containing a script or ticket number.
3. The following transactions were found to be missing from the transaction create tests and need to be added:

- [x] EARMARK_MEMO
- [x] INDIVIDUAL_JF_TRANSFER_MEMO
- [x] INDIVIDUAL_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO
- [x] INDIVIDUAL_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO
- [x] PAC_JF_TRANSFER_MEMO

- [x] PAC_NATIONAL_PARTY_RECOUNT_ACCOUNT
- [x] PAC_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO
- [x] PARTY_JF_TRANSFER_MEMO
- [x] TRIBAL_JF_TRANSFER_MEMO
- [x] TRIBAL_NATIONAL_PARTY_RECOUNT_JF_TRANSFER_MEMO
- [x] PAC_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO
- [x] INDIVIDUAL_RECOUNT_RECEIPT
- [x] TRIBAL_RECOUNT_RECEIPT
- [x] PAC_RECOUNT_RECEIPT
- [x] PARTY_RECOUNT_RECEIPT
- [x] TRIBAL_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO

**Acceptance Criteria**
The Cypress e2e report displays site features in output rather than sprint and ticket numbers. Transaaction create tests include the ones listed above in Task 3.

**QA Notes**
These transaction were completed before Sprint 17 Started.
Screen shots in comments show new names of test suites and the new output text of the e2e report output.

### DEV Notes ###
null

### Design ###
null

[FECFILE-891](https://fecgov.atlassian.net/browse/FECFILE-891)

**Comment by WiseQA** [comment]
@mjtravers naming of this transaction needs to match the ticket name in both accordion dropdown and Title of Transaction page.

Correct Naming is: 
Joint Fundraising Transfer - National Party Recount/Legal Proceedings Account 

Accordion dropdown needs changed to naming of ticket (see below what is being displayed)
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8a2b0f92-9be2-480b-a1f7-a76fc60b31de)

Title on Transaction MePage needs changed to naming of ticket (see below what is being displayed)

**Comment by mjtravers** [comment]
This ticket is needed to refactor the test suite names from the current sprint/ticket naming convention to a functionality naming convention. Reopening ticket.

**Comment by Elaine-Krauss-TCG** [comment]
4 Transactions added to E2E coverage
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/1fde8621-0342-46b0-8306-6c4bb73ebcd6)

**Comment by Elaine-Krauss-TCG** [comment]
The layout of the E2E tests within the cypress directory has been updated as well as the names of each of the tests.
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/c39a2c3d-da56-4749-9f67-2c79ff40ed0e)

**Comment by Elaine-Krauss-TCG** [comment]
3 E2E tests have been broken by recent changes

- [x] Contacts are editable by transactions
- [x] Parent Transaction ID's are visible in the transaction management table
- [x] Transaction accordion layout

**Comment by Elaine-Krauss-TCG** [comment]
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/0ee489dd-0e14-4178-b535-16fb471fbd5d)

**Comment by mjtravers** [comment]
Passes CR. Ready for screenshot visual check in QA.

**Comment by WiseQA** [comment]
QA review verified as a visual inspection from the screenshots show new names of test suites and the new output text of the e2e report output.

QA Review Completed.   Moved to Stage Ready.
