### ISSUE TITLE
Update Contribution Purpose Description label for Schedule A Transactions

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#836]
***Task:*** "Contribution Purpose Description" should read "Purpose of Receipt" for Schedule A Transactions.

### QA Notes ###
List of Schedule A transaction groups for testing:
- Individual Receipt (Group A) Note:  Optional
- Offsets to Operating Expenditures (Group B) Note:  Optional
- Other Receipts (Group C) Note:  Optional (Updated from Other Receipt to Other Receipts in QA Notes)
- Tribal Receipt (Group D) Note:  System Generated
- Joint Fundraising Transfer (Group E) Note:  System Generated
- PAC Joint Fundraising Transfer Memo (Group F) Note:  System Generated
- Earmark Receipt/Memo (Group G) Note:  System Generated

Updated Note to QA this field is "Optional" for all above transactions

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-871](https://fecgov.atlassian.net/browse/FECFILE-871)

**Comment by Elaine-Krauss-TCG** [comment]
A new system has been put in place where the purpose description field's title takes on different values depending on the schedule.  Alternatively, this can be overridden by providing a specific title to use.

Example from an Individual Receipt:
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/11334410-53d8-497d-97b8-b425c85885d2)

**Comment by Elaine-Krauss-TCG** [comment]
This has been implemented for the following transaction groups:

- [x] Individual Receipt (Group A)
- [x] Offsets to Operating Expenditures (Group B)
- [x] Other Receipt (Group C)
- [x] Tribal Receipt (Group D)
- [x] Joint Fundraising Transfer (Group E)
- [x] PAC Joint Fundraising Transfer Memo (Group F)
- [x] Earmark Receipt/Memo (Group AG)

**Comment by Elaine-Krauss-TCG** [comment]
Reimplemented to work with the Schedule B refactor
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/12aec081-f1e9-4009-8028-e348fb27dcda)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by WiseQA** [comment]
QA Review Verified the following transactions Contribution Purpose Description field label has been changed to "Purpose of Receipt (Optional)".

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/175eb228-8b3f-4088-822d-ff6a6e129e98)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/37d222e6-3541-41e3-afa1-e1b6f10dc1bc)

Updated QA notes / Acceptance Criteria from Other Receipt to Other Receipts.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/010760e8-bd8f-4192-88a0-ef7a1945af82)

Tribal Receipt showing (System Generated) not denoted in QA notes or Acceptance this should not be Optional

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/bae5ad95-d3c0-4b7b-9841-e353665cf866)

Joint Fundraising Transfer  showing (System Generated) not denoted in QA notes or Acceptance this should not be Optional

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2cfdcce8-b42a-46ef-98f5-04e06e6fe5d8)

PAC Joint Fundraising Transfer Memo showing (System Generated) not denoted in QA notes or Acceptance this should not be Optional

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/77e28b29-8ac2-4c4a-abfb-4d1d180a251e)

Earmark Receipt/Memo showing (System Generated) not denoted in QA notes or Acceptance this should not be Optional
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/806b69ae-368f-424b-b258-7019eb1a3a46)

Updated QA Notes to reflect what screens are populated with Optional and System Generated.

QA Review Completed as ticket is written.   Moved to Stage Ready.
